# Generated by Django 4.2.7 on 2025-10-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='prev_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='hash_value',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.order'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionlog',
            unique_together={('order', 'timestamp')},
        ),
    ]
